language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
install:
  - composer self-update
  - composer install --dev
script:
  - vendor/bin/robo test:coverage-codeclimate
addons:
  code_climate:
    repo_token: 26661f402d5d329c0022c8bf8db70b94e5b8e7d5b2c0dca909cbf47e5f2edaf8
after_success:
  - vendor/bin/test-reporter
